# Generated by Django 6.0.4 on 2026-04-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("point_of_sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=20
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=20
            ),
        ),
    ]
